name: Deploy to Amplify Hosting

on:
  push:
    branches: [develop, uat, sit, release]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: develop
            env: devnonprod
          - branch: uat
            env: uatnonprod
          - branch: sit
            env: sitnonprod
          - branch: release
            env: prod

    # Chỉ chạy khi branch khớp item matrix
    if: ${{ github.ref_name == matrix.branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install
        run: npm ci || npm install

      - name: Build
        run: npm run build

      # Cấu hình AWS bằng long-lived keys (đơn giản nhất)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Amplify CLI
        run: npm i -g @aws-amplify/cli

      - name: Amplify version
        run: amplify --version

      # Checkout đúng env (đã tạo sẵn & commit metadata)
      - name: Checkout Amplify env
        run: amplify env checkout ${{ matrix.env }} --yes

      # Publish + Invalidate CloudFront cache
      - name: Publish to Amplify Hosting
        run: amplify publish --invalidateCloudFront --yes
